internfair_iitg/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("internfair.urls")),
    path("recruiter/", include("recruiter.urls")),
    path('admin/', admin.site.urls),
]

recruiter/urls.py
from django.urls import include, path,re_path
from . import views
from internfair import views as stViews

app_name = 'recruiter'

urlpatterns = [

    path('', views.RecruiterLanding, name='RecruiterLanding'),
    path('registration', stViews.StartUpsRegistration.as_view(), name='RecruiterRegistration'),

    path(r'^interns/(?P<pk>\d+)/$', views.AvailableInterns, name='InternList'),
    path('shortlist/', views.ShortlistedInterns, name='shortlistedInterns'),
    path('shortlist/<int:pk>/', views.ShortlistedInterns, name='shortlistedInterns'),
    path(r'^profile/(?P<pk>\d+)/$', views.CompanyProfile, name='Profile'),
    path(r'^profile/edit/(?P<pk>\d+)/$', views.EditStartupProfile, name='editStartupProfile'),
    path('profile/deactivate/<int:pk>', views.DeactivateForm, name='deactivate'),
    path('form', views.intern_form, name='form_submit'),
    path('login',stViews.startupLogin, name='StartupLogin'),
    path('logout',views.logout_view, name='StartupLogout'),

]

recruiter/models.py
from django.db import models
from internfair.models import *
# Create your models here.

class Intern_form(models.Model):
    startup = models.ForeignKey(StartUps, on_delete=models.CASCADE, related_name='intern_details')
    profile = models.CharField(max_length=50,blank=True)
    stipend = models.IntegerField(blank=True)
    location = models.CharField(max_length=50,blank=True)
    allowances = models.CharField(max_length=150,blank=True)
    questions = models.TextField(max_length=200)
    status = { ('ACTIVE','ACTIVE'),('DEACTIVE','DEACTIVE')}
    FormStatus = models.CharField(max_length=10,choices=status,default='ACTIVE')
    remarks = models.CharField(max_length=200,default=".")
    def string_as_list(self):
        # print(self.questions)
        ques = self.questions.split(',')
        # print(ques)
        for q in ques:
            if q == '':
                ques.remove(q)
        print(ques)
        return ques


    def __str__(self):
        return str(self.startup.user) + '-' +self.profile

    def Applicant_count(self):
        available = InternApplication.objects.filter(Internship__startup=self.startup).filter(Internship__profile=self.profile).filter(
            Status="PENDING").count()
        return available
    def Shortlisted_count(self):
        shortlisted = InternApplication.objects.filter(Internship__startup=self.startup).filter(Internship__profile=self.profile).filter(
            Status="SHORTLISTED").count()
        return shortlisted


class InternApplication(models.Model):
    status = { ('PENDING','pending'),('SHORTLISTED','shortlisted'),('REJECTED','rejected')}
    Intern = models.ForeignKey(Students,on_delete=models.CASCADE)
    Internship = models.ForeignKey(Intern_form,on_delete = models.CASCADE)
    Status = models.CharField(max_length=20,choices=status,default='PENDING')
    Answers = models.TextField(max_length=400)
    CV  = models.CharField(max_length=500,default="not submitted")
    def __str__(self):
        return '{}-{}'.format(self.Intern,self.Internship)

    def count_intern_Answers(self):
        ans = self.Answers.strip('[]')
        ans_list = ans.split(',')
        # print(ans_list)
        len(ans_list)
        # print(len)
        # print(self.questions)
        ques = self.Internship.questions
        # print(ques)
        ques_list = ques.split(',')
        # print(ques)
        # print(ques)
        for q in ques_list:
            if q == '':
                ques_list.remove(q)
        # print(ques_list)

        QnA = dict(zip(ques_list,ans_list))
        return QnA

    def if_shortlisted(self):
        if self.Status == 'SHORTLISTED':
            print(self.Status, 'congrats')
            return True
        else:
            return False

recruiter/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login, logout,authenticate
from django.http import HttpResponse
from internfair.models import *
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required
# Create your views here.
from internfair.models import *
from .models import *


def RecruiterLanding(request):
    template = "recruiter/RecruiterLanding.html"
    return render(request,template)


# def RecruiterRegistration(request):
#     template = "recruiter/RecruiterRegistration.html"
#     return render(request, template)

@login_required(login_url='/recruiter')
def AvailableInterns(request,**kwargs):

    startup_object = StartUps.objects.get(user=request.user)
    template = "recruiter/AvailableInterns.html"

    Applications = InternApplication.objects.filter(Internship__startup = startup_object).filter(Status="PENDING")
    context = {'startup': startup_object, 'app': Applications}

    return render(request, template,context)


@login_required(login_url='/recruiter')
def ShortlistedInterns(request,**kwargs):
    if request.user.is_authenticated:
        startup_object = StartUps.objects.get(user=request.user)
        AllApplications = InternApplication.objects.filter(Internship__startup=startup_object)
        Applications = AllApplications.filter(Status='SHORTLISTED')
        template = "recruiter/ShortlistedInterns.html"
        if kwargs:

            pk = kwargs['pk']
            # print(pk)
            intern = AllApplications.get(id = pk)

            intern.Status = 'SHORTLISTED'
            intern.save()

        return render(request, template,{'startup': startup_object, 'app': Applications})
    else:
        return redirect('recruiter:RecruiterLanding')


def add_profiles(request):
    template = "recruiter/AvailableInterns.html"
    return render(request, template)


@login_required
def CompanyProfile(request,**kwargs):
    current_user = request.user
    startup_object = StartUps.objects.get(user=current_user)
    profiles = Intern_form.objects.filter(startup_id = startup_object.id).filter(FormStatus = 'ACTIVE')
    template = "recruiter/CompanyProfile.html"
    return render(request, template,{'startup': startup_object,'profiles':profiles})

@login_required
def DeactivateForm(request,pk):

    id = pk
    current_user = request.user
    startup_object = StartUps.objects.get(user=current_user)
    form = Intern_form.objects.get(pk = id)
    print(form)
    form.FormStatus = 'DEACTIVE'
    form.save()
    return HttpResponseRedirect(reverse('recruiter:Profile',kwargs={'pk': request.user.id}))

@login_required
def EditStartupProfile(request, **kwargs):
    current_user = request.user
    startup = StartUps.objects.get(user=current_user)
    if request.method=='POST':
        if request.POST['companyName']:
            startup.companyName = request.POST['companyName']
        if request.POST['description']:
            startup.description = request.POST['description']
        if request.POST['location']:
            startup.location = request.POST['location']
        if request.POST['logo']:
            student.logo = request.POST['logo']
        print(request.POST)
        startup.save()
    return HttpResponseRedirect(reverse('recruiter:Profile',kwargs={'pk': current_user.id}))





@login_required
def intern_form(request):

    if request.method == "POST":
        print(request.POST)
        startup = StartUps.objects.get(user=request.user)
        profile = request.POST["PROFILE"]
        stipend = request.POST["STIPEND"]
        allowances = request.POST["ALLOWANCE"]
        location = request.POST["LOCATION"]
        remarks = request.POST["REMARKS"]
        questions =  f'{request.POST["Q1"]},{request.POST["Q2"]},{request.POST["Q3"]}'

        form = Intern_form.objects.create(startup = startup,profile=profile,stipend=stipend,allowances=allowances,location=location,questions=questions,remarks = remarks)
        form.save()
        print(form)
        return HttpResponseRedirect(reverse('recruiter:Profile',kwargs={'pk': request.user.id}))


@login_required
def logout_view(request):
    logout(request)
    return redirect('recruiter:RecruiterLanding')

recruiter/templates/recruiter/AvailableInterns.html
{% extends "recruiter/base1.html" %}

{% load static %}

<html>
<head>
  <title>{% block title %} Available Interns {% endblock %} </title>
</head>

<body>

{% block content  %}
<script src="https://cdn.jsdelivr.net/npm/jdenticon@3.0.1" async></script>

  <div class="row mb-3 justify-content-between">
    <div class="col-md-8 pb-4 ml-sm-5 pb-md-0 highlight">
      <a  href="#" >Available Interns |</a>
      <a class=" light-text"   href="{% url 'recruiter:shortlistedInterns' %}" >Shortlisted Interns</a>
    </div>
  </div>


  <div class="row d-none d-md-flex" id="table-head">
      <div class="col-md-auto profile-userpic padding"><img src="https://www.htmlcsscolor.com/preview/128x128/FFFFFF.png" class="img-fluid"></div>
      <div class="col-md">
        <div class="row light-text">
          <div class="col padding">NAME</div>
          <div class="col padding">PROFILE</div>
          <div class="col padding">DEPARTMENT</div>
        </div>

      </div>
    </div>



    {% for intern in app %}
      <div class="row p-2 p-md-0 top" >
      <div class="col-3 col-md-auto  padding pt-3 mx-3 m-md-0">
<!--          <img src="https://cdn130.picsart.com/321379439036201.jpg?type=webp&to=crop&r=256" class="img-fluid">-->
      <svg data-jdenticon-value="user127{{intern.id }}" width="30" height="30">
        Fallback text or image for browsers not supporting inline svg.
      </svg>
      </div>
      <div class="col-auto col-md p-0 px-md-3 " data-target="#model{{ intern.id }}" data-toggle="modal">
        <div class="row flex-column flex-md-row  justify-content-center " style="height: 100%;">


            <!--a href="#model{{ intern.id }}" data-toggle="modal"-->
              <div class="col-md-4 padding">{{ intern.Intern.name }}</div>

              <div class="col-md-4 padding">{{ intern.Internship.profile }}</div>
              <div class="col-md-4 padding">{{ intern.Intern.department }}</div>
          
        </div>
      </div>
    </div>


    <!------------------------------------------modal for internanswercard --------------------------------->




     <div class="modal fade  " id="model2{{ intern.id }}">
      <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable ">
        <div class="modal-content border">
            <h3 class="modal-title pl-4 pt-4"><b>{{ intern.Intern.name }}</b></h3>
          <div class="modal-body">
              {% for key,value in intern.count_intern_Answers.items %}
              <p> <h7  style="color:#416EA8!important;"> Q : {{ key }}</h7><br>
                  <h7 >{{ value }}</h7></p>
              {% endfor %}



          <div class="pb-1 mx-1 ">

                <a href='#model{{ intern.id }}' class='btn mx-2 px-5 my-2 btn-outline-primary border-lg ' data-toggle='modal' data-dismiss="modal" >View profile</a>
                <a href="{% url 'recruiter:shortlistedInterns' intern.id %}" class='btn mx-2 px-5 my-2 btn-primary border-lg '>Shortlist</a>

          </div>

        </div>
      </div>
     </div>
    </div>


    <!-------------------------intern profile card ------------------------------------------------------------------->



     <div class="modal fade  " id="model{{ intern.id }}">
      <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable ">
        <div class="modal-content border">

          <h3 class="modal-title pl-3 pt-3 "><b>{{ intern.Intern.name }}</b></h3>
          <div class="modal-body">


              <div class="pb-3 pt-2 mx-auto" style="max-width:30%;">
<!--                <img src="{% static 'image/test_image_ecell.jpg' %}" class="rounded-circle img-fluid" alt="">-->
               <svg data-jdenticon-value="user127{{intern.id }}" width="80" height="80"></svg>

              </div>


              <p><h7 style="color:#416EA8!important;">DEPARTMENT</h7><br>{{ intern.Intern.department }}</p>
              <p><h7 style="color:#416EA8!important;">ROLL NO.</h7><br>{{ intern.Intern.roll_number }}</p>
              <p><h7 style="color:#416EA8!important;">CV</h7><br><a href="{{ intern.CV }} " >Student CV</a></p>

            <div class="pb-3 mx-2 ">

                <a href='#model2{{ intern.id }}' class= 'btn px-3 mx-3 my-2 btn-outline-primary border-lg' data-dismiss='modal' data-toggle="modal">View Answers to form</a>
                <a href="{% url 'recruiter:shortlistedInterns' intern.id %}" class='btn  mx-3 px-5 my-2 btn-primary border-lg '>Shortlist</a>

            </div>

          </div>
        </div>
      </div>
     </div>

    {% endfor %}
 {% endblock %}

<!---------------------------------------------------------------->



</body>
</html>

recruiter/templates/recruiter/CompanyDetailsCard.html
{% load static %}

<html>

<body>
      <form method="POST" action="{% url 'recruiter:form_submit' %}">
                        {% csrf_token %}
        <div class="modal fade " id="myModal"  role="dialog" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable " role="document">
                <div class="modal-content ">
                     <h2 class="modal-header mx-auto">Internship Form</h2>

                    <div class="modal-body">
                        <div class="form-group">


                            <h4>Company Bio</h4>
                     
                       <!----created new form ------------>


                    <label for="question1" class="question" >PROFILE</label>
                    <div class="form-group">
                        <input type="text" class="form-control" id="question1" name="PROFILE">
                    </div>
                    <label for="question2" class="question">STIPEND</label>
                    <div class="form-group">
                        <input type="text" class="form-control" id="question2" name="STIPEND">
                    </div>
                    <label for="question3" class="question">LOCATION</label>
                    <div class="form-group">
                        <input type="text" class="form-control" id="question3" name="LOCATION">
                    </div>
                    <label for="question4" class="question">ALLOWANCE</label>
                    <div class="form-group">
                        <input type="text" class="form-control" id="question4" name="ALLOWANCE">
                    </div>
                    <label for="question5" class="question">REMARKS</label>
                    <div class="form-group">
                        <input type="text" class="form-control" id="question5" name="REMARKS" >
                    </div>
                <div class="modal-footer mx-auto">


                    <a class="btn btn-primary" href="#myModal2"    data-toggle='modal' data-dismiss="modal"  >Next</a>

                  <button type="button" class="btn btn-outline-primary " data-dismiss="modal" >Back</button>


                </div>

                </div>
              </div>
            </div>
          </div>
         </div>










        <div class="modal fade " id="myModal2"   >
                <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable " role="document">
                    <div class="modal-content ">
                            <h2 class="modal-header mx-auto">Internship Form</h2>

                        <div class="modal-body">
                            <div class="form-group">
            <div class="">
                <div style="padding: 5%;">
                    <div style="text-align: center;">

                    </div>

                    <span class="sub-heading">Question for preliminary interview</span>
                   
                        <br>
                        <span class="Qheading">Question 1</span>
                        <input type="text" class="input" name="Q1">
                        <br><br>
                        <span class="Qheading">Question 2</span>
                        <input type="text" class="input" name="Q2">
                        <br><br>
                        <span class="Qheading">Question 3</span>
                        <input type="text" class="input" name="Q3">
                        <br><br>

                    <br>
                        <br>
                    <div class="row align-items-center ">
                        <div class="col-5 text-right"><a href="#myModal"  class="back"  data-toggle="modal" data-dismiss="modal">Back</a></div>
                        <div class="col-7 text-left"><input type="submit" class="Publish" value="Publish"></div>
                    </div>

                </div>

            </div>
        </div>
                        </div>
                    </div>
                </div>
        </div>
 </form>

   {% include  "recruiter/js.html" %}

</body>
</html>

recruiter/templates/recruiter/CompanyProfile.html
{% extends "recruiter/base1.html" %}

{% load static %}
<html lang="en">
  <head>
    <title>{% block title %}Company Profile {% endblock %}</title>
  </head>
  <body>

    {% block content %}

     <div class="row mb-3 justify-content-between">
        <div class="col-md-6 pb-4 pb-md-0 highlight">
            Active Forms
        </div>
    </div>






     <div class="container">
           <div class="row d-none d-md-flex" id="table-head">
               <div class="col-md-auto profile-userpic padding"><img src="https://www.htmlcsscolor.com/preview/128x128/FFFFFF.png" class="img-fluid"></div>
               <div class="col-md">
                 <div class="row light-text">
                   <div class="col padding">PROFILE</div>
                   <div class="col padding">STIPEND</div>
                   <div class="col padding">LOCATION</div>
                   <div class="col padding">APPLICANTS</div>
                 </div>

               </div>
             </div>


         {% for p in profiles %}
             <div class="row p-2 p-md-0 top" >
             <div class="col-3 col-md-auto profile-userpic padding p-0 mx-3 m-md-0"><img src="https://cdn130.picsart.com/321379439036201.jpg?type=webp&to=crop&r=256" class="img-fluid"></div>
             <div class="col-auto col-md p-0 px-md-3 " data-target="#model{{p.id}}" data-toggle="modal">
               <div class="row flex-column flex-md-row  justify-content-center " style="height: 100%;">


                   <!--a href="#model{{ intern.id }}" data-toggle="modal"-->
                     <div class="col-md-3 padding">{{ p.profile }}</div>
                     <div class="col-md-3 padding">{{p.stipend}} INR</div>
                     <div class="col-md-3 padding">{{p.location}}</div>
                     <div class="col-md-3 padding">{{ p.Applicant_count }}</div>

               </div>
             </div>
           </div>



        <!-- Modal -->
          <div class="modal fade" id="model{{p.id}}"  role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                    <div class="title">
                       {{ p.profile }}
                    </div>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                  <div class="modal-body">
                    <label for="question1" style="color:#416EA8!important;" >APPLICANTS</label>
                    <p id="question1">{{ p.Applicant_count }}</p>
                    <label for="question2" style="color:#416EA8!important;">SHORTLISTED</label>
                    <p id="question2">{{ p.Shortlisted_count }}</p>
                  </div>
                <div class="modal-footer mx-auto">
                  <a href="{% url 'recruiter:deactivate' p.id %}" type="button" class="btn btn-outline-primary "  >Deactivate form</a>
                </div>


              </div>
            </div>
          </div>
         {% endfor %}
     </div>





    {% endblock %}


  </body>
</html>

recruiter/templates/recruiter/RecruiterLanding.html
   
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">    
    <title>Home-Recruiter</title>
    <script type='text/javascript' src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type='text/javascript' src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'recruiter/css/RecruiterLanding.css' %}">

</head>
<body>
    <nav class="navbar navbar-edit navbar-expand-lg navbar-light bg-light" style="padding: 1vh 8vw; box-shadow: 0px 2px 8px rgba(72, 74, 82, 0.08); background-color: #FFFFFF !important">
        <a class="brand" href="#" id="brand">Internfair</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse drop-menu" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="menu-item">
                <a href="#" class="nav-menu" style="margin-right: 8vw;">Home</a>
            </li>
            <li class="menu-item">
                <a href="mailto:internfair@udgam-iitg.ac.in" title="Send us Mail with any of your Query, We will respond you, at our earliest."class="nav-menu">Contact Us</a>
            </li>
          </ul>
          <a href="{% url 'recruiter:RecruiterRegistration' %}"><button class="RegisterBtn">Register</button></a>
          
        </div>
      </nav>

      <br><br><br>
      <div class="container">
        <div class="row justify-content-center align-items-center" style="margin-top:5vh">
            <div class="col-lg-5 order-lg-1 order-md-1 order-12 col-md-6 col-10 temp" style="padding-left:10vw;">
                <span class="heading">Interested in Recruiting Students who push their limits?</span>
                <br><br>
                <span class="quote">Internfair provide perfect platform to connect with them</span>
                <br><br><br>
                <div class="form" style="width: 80%;">
                    <div class="row justify-content-end">
                        <div class="col-6">
                            <span class="studentLogin">Recruiter Login</span>
                        </div>
                        <div class="col-6 text-right">
                            <a class="recruiter" href="{% url 'index' %}">I am a student</a>
                        </div>
                    </div>
                    <form method='POST' action='../recruiter/login'>
                        {% csrf_token %}
                        <input type="text" name='username' placeholder="Username" class="input">
                        <input type="password" name='password' placeholder="Password" class="input">
                        <input type="submit" value="Login" class="login">
                    </form>
                    
                    <div class="row justify-content-end" style="margin-top: 24px;">
                        <div class="col-6">
                            <span class="recruiter"><a href="{% url 'recruiter:RecruiterRegistration' %}">Don’t have an account?</a></span>
                        </div>
                        <div class="col-6 text-right">
                            <a class="recruiter" href="mailto:internfair@udgam-iitg.ac.in?subject=Send Me Password " title="Please Send a Mail with your Email id and Username, You will get it on mail">Forgot Password?</a>
                        </div>
                    </div>
                    
                </div>
                
                {% if error %}
                        <br>
                        <div class="row" style="padding-left:15px">
                        <div class="error col-9">
                        {{error}}
                        </div>
                        </div>
                        
                {% endif %}
             
            
            </div>
            <div class="col-lg-7 order-lg-2 order-md-2 order-1 text-center col-md-6 col-12" id="intro"  >
                <img class="sideImg" src="{% static 'image/sideImg.png' %}" alt="">

            </div>
       </div>
      </div>

      
</body>
</html>

recruiter/templates/recruiter/base1.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<script src="https://cdn.jsdelivr.net/npm/jdenticon@3.0.1" async></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'recruiter/css/AvailableInterns.css' %}">
   <link rel="stylesheet" href="{% static 'recruiter/css/theme_config.css' %}" >
     <link rel="stylesheet" href="{% static 'recruiter/css/InternshipQuestionsCard.css' %}">

  <title>{% block title %}base {% endblock %} </title>
</head>

<body>

  <nav class="navbar navbar-expand-md navbar-light fixed-top py-2 p-md-0" id="main-navbar">
    <div class="container d-flex" style="height: 100%;">
      <div class="col-4">
        <span>Recruiter's page</span>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="col collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav m-0 d-flex justify-content-around" style="width: 100%;">
          <li class="nav-item active py-md-2 ">
            <a class="nav-link " href="{% url 'recruiter:Profile' startup.id %}">Dashboard<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active py-md-2">
            <a class="nav-link" href="{% url 'recruiter:InternList' startup.id %}">Internship Statistics</a>
          </li>
          <li class="nav-item active py-md-2">
            <a class="nav-link" href="mailto:internfair@udgam-iitg.ac.in" title="Send us Mail with any of your Query, We will respond you, at our earliest.">Contact Us</a>
          </li>
          <li class="nav-item active py-md-2">
            <a class="nav-link" href="{% url 'recruiter:StartupLogout' %}" style="color: #416EA8;">Log Out</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>


  <div class="container">
    <div class="row" style="margin-top: 6rem;">
      <div class="col-12 col-md-2 d-flex justify-content-center align-items-center">
<!--          <img src="https://demo.appcarvers.com/junite/media/com_easysocial/photos/1606/4686/google-logo-icon-png-transparent-background_thumbnail.png" id="logo">-->
      <svg data-jdenticon-value="user17{{startup.id }}" width="80" height="80">

      </svg>
      </div>
    <div class="col-md-4 pb-3 pb-md-0">
      <h1 id="company-name">{{startup.companyName}}</h1>
      <div class="light-text" style="font-size: .75rem;">COMPANY DESCRIPTION</div>
      <p style='padding-right:10px'>{{startup.description}}</p>
      <div class="light-text" style="font-size: .75rem;">LOCATION</div>
      <p>{{startup.location}}</p>
      <a href= "#edit_profile" data-toggle="modal"  style="color: #416EA8; font-size: .75rem;">Edit Profile</a>
    </div>
    <div class="col-md-4 d-flex align-items-center">
      <div>
        <p>Add a new internship position to start recruiting</p>
                {% include "recruiter/CompanyDetailsCard.html" %}

      <a class="btn btn-custom btn-responsive" href="#myModal" role="button"  data-toggle="modal">

          Add an internship form</a>
      </div>

    </div>
  </div>
    <hr class="line">
  </div>



   <div class="container">
             <div class="modal fade" id="edit_profile" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered  " role="document">
              <div class="modal-content">
                <div class="modal-header">
                    <div class="mx-auto " >
                    <b>Edit profile</b>
                    </div>

                </div>
                <form method='POST' action="{% url 'recruiter:editStartupProfile' startup.id %}">
                {% csrf_token %}
                    <div class="prelim mx-auto">
                     <div class="pb-3 pt-2 mx-auto" style="max-width:30%;">
<!--                        <img src="{% static 'image/p.png' %}" class="rounded-circle img-fluid" alt="">-->
                     <svg data-jdenticon-value="user17{{startup.id }}" width="80" height="80"></svg>
                     </div>
                      <div class='text-center'>
                         <button class=" btn btn-sm   btn-primary submit " onclick="document.getElementById('getFile').click()">Upload/Change Company Photo</button>
                      </div>
                     <input type='file' id="getFile" style="display:none">
                </div>
                    <label for="question1" class="question" >COMPANY NAME</label>
                    <div class="form-group">
                        <input type="text" class="form-control" name='companyName' value='{{startup.companyName}}' id="question1" >
                    </div>
                    <label for="question2" class="question">COMPANY DESCRIPTION</label>
                    <div class="form-group">
                        <input type="text" name='description' maxlength='500' value='{{startup.description}}' class="form-control" id="question2">
                    </div>
                    <label for="question3" class="question">COMPANY LOCATION</label>
                    <div class="form-group">
                        <input type="text" name='location' value='{{startup.location}}' class="form-control" id="question3" >
                    </div>
                <div class=" text-center" style='padding-bottom:10px'>
                    <button type="submit" class="btn btn-primary "  >Save Changes</button>
                  <button type="button" class="btn btn-outline-primary " data-dismiss="modal" >No</button>
                </div>
                </form>

              </div>
            </div>
          </div>
         </div>
    <div class="container">
    {% block content  %}
        {% endblock %}
    </div>
   {% include  "recruiter/js.html" %}

  </body>



  </html>