internfair/urls.py
from django.urls import include, path
from . import views
from django.shortcuts import  render
urlpatterns = [
    path('', views.index, name='index'),

    path('student/register', views.StudentRegistration.as_view(), name='StudentRegistration'),
    path('student/profile', views.StudentProfile, name='StudentProfile'),

    # path('student/register/', views.StudentRegistration.as_view(), name='StudentRegistration'),
    path(r'^student/profile/(?P<pk>\d+)/$', views.StudentProfile, name='StudentProfile'),
    path(r'^student/profile/edit/(?P<pk>\d+)/$', views.EditStudProfile, name='editStudentProfile'),
    path('student/profile/delete/<int:pk>',views.delete_app,name='delete_app'),
    path('student/availableInternships', views.AvailableInternships, name='AvailableInternships'),
    path('student/login', views.studentLogin, name='StudentLogin'),
    path('student/logout', views.logout_view, name='StudentLogout'),
]

internfair_iitg/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("", include("internfair.urls")),
    path("recruiter/", include("recruiter.urls")),
    path('admin/', admin.site.urls),
]

recruiter/urls.py
from django.urls import include, path,re_path
from . import views
from internfair import views as stViews

app_name = 'recruiter'

urlpatterns = [

    path('', views.RecruiterLanding, name='RecruiterLanding'),
    path('registration', stViews.StartUpsRegistration.as_view(), name='RecruiterRegistration'),

    path(r'^interns/(?P<pk>\d+)/$', views.AvailableInterns, name='InternList'),
    path('shortlist/', views.ShortlistedInterns, name='shortlistedInterns'),
    path('shortlist/<int:pk>/', views.ShortlistedInterns, name='shortlistedInterns'),
    path(r'^profile/(?P<pk>\d+)/$', views.CompanyProfile, name='Profile'),
    path(r'^profile/edit/(?P<pk>\d+)/$', views.EditStartupProfile, name='editStartupProfile'),
    path('profile/deactivate/<int:pk>', views.DeactivateForm, name='deactivate'),
    path('form', views.intern_form, name='form_submit'),
    path('login',stViews.startupLogin, name='StartupLogin'),
    path('logout',views.logout_view, name='StartupLogout'),

]

internfair/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from django.db.models.signals import post_save,post_delete
from django.dispatch import receiver
import os


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.student.user.id, filename)

def user_directory_path1(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.id, filename)

class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_startup = models.BooleanField(default=False)

class StartUps(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    POC = models.CharField(max_length=50)
    email = models.EmailField(max_length=150)
    companyName = models.CharField(max_length=100, default="")
    contact = models.CharField(default="",max_length=10)
    logo = models.ImageField(upload_to=user_directory_path1,blank=True)
    description = models.CharField(max_length=500, default="Edit Profile to add description")
    location = models.CharField(max_length=100, default="Edit profile to add location")

    def __str__(self):
        return self.user.username

class Students(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,related_name='student')
    name = models.CharField(max_length=50,default="")
    roll_number = models.CharField(default="",max_length=13)
    department = models.CharField(max_length=50,default="")
    email = models.EmailField(max_length=150,default="")
    contact = models.CharField(default="",max_length=10)
    bio = models.CharField(default="Edit Profile to add bio",max_length=500)
    profilePhoto = models.ImageField(upload_to=user_directory_path,blank=True)
    intern_count = models.IntegerField(default=0)
    def __str__(self):
        return self.user.username

internfair/forms.py
from django import forms
from internfair.models import *
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
from django.db import transaction

class StartUpsForm(UserCreationForm):
    email = forms.EmailField(max_length=150)
    POC = forms.CharField(max_length=50)
    contact = forms.IntegerField(label='Contact No.')
    companyName = forms.CharField(max_length=100)
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username','email','POC','contact','companyName','password1', 'password2',)   

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_startup = True
        user.save()
        startup = StartUps.objects.create(user=user)
        startup.email=self.cleaned_data.get('email')
        startup.POC=self.cleaned_data.get('POC')
        startup.companyName=self.cleaned_data.get('companyName')
        startup.contact=self.cleaned_data.get('contact')
        startup.save()
        return user

class StudentsForm(UserCreationForm):
    name = forms.CharField(max_length=100)
    roll_number = forms.CharField(max_length=13)
    email = forms.EmailField(max_length=150)
    department = forms.CharField(max_length=50)
    contact= forms.CharField(max_length=10, required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('name','username','email','roll_number','department','contact','password1', 'password2',)
    
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student =Students.objects.create(user=user)
        student.name=self.cleaned_data.get('name')
        student.roll_number=self.cleaned_data.get('roll_number')
        student.email=self.cleaned_data.get('email')
        student.department=self.cleaned_data.get('department')
        student.contact=self.cleaned_data.get('contact')
        student.save()
        return user

class ApplicationForm(forms.Form):
    resume = forms.FileField()
    content = forms.CharField(max_length=100)

class LogoForm(forms.Form):
    logo = forms.ImageField()

    

internfair/views.py
from django.contrib.auth import login, logout,authenticate
from django.shortcuts import redirect, render
from django.views import View
from .forms  import *
from django.http import HttpResponse
from django.views.generic import CreateView
from django.contrib.auth.forms import AuthenticationForm
from .models import *
from recruiter.models import *
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    return render(request, "StudentLanding.html")

class StudentRegistration(CreateView):
    model = User
    form_class = StudentsForm
    template_name = './StudentRegistration.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        givenemail = str(form.cleaned_data.get('email'))
        print(givenemail)
        iitgmail = "iitg.ac.in"
        if iitgmail in givenemail :
            user = form.save()
            login(self.request, user)
            return HttpResponseRedirect(reverse('StudentProfile',kwargs={'pk': user.id}))

        else:
            messages.info(self.request, 'Please Enter IITG webmail id only.')
            return redirect('StudentRegistration')



class StartUpsRegistration(CreateView):
    model = User
    form_class = StartUpsForm
    template_name = 'recruiter/RecruiterRegistration.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'startup'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return HttpResponseRedirect(reverse('recruiter:Profile',kwargs={'pk': user.id}))

@login_required
def StudentProfile(request,**kwargs):

    user = Students.objects.get(user=request.user)
    registered_internships = InternApplication.objects.filter(Intern__id = user.pk)
    print(registered_internships)
    return render(request, "StudentProfile1.html",{'student':user,'interns':registered_internships})


def studentLogin(request):
    if request.method == 'POST':
        username = request.POST.get('Username')
        password = request.POST.get('Password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_student:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('StudentProfile',kwargs={'pk': user.id}))
                else:
                    return render(request, "StudentLanding.html",{'error':'User is flagged Inactive. Drop mail to internfair@udgam-iitg.in to reactivate your account'})
                # return redirect('/student/profile',kwargs={'pk': user.id})
            else:
                return render(request, "StudentLanding.html",{'error':'Invalid login details entered. If you are a recruiter, login at recruiter page.'})
        else:
            return render(request, "StudentLanding.html",{'error':'Invalid login details entered.'})
            # return redirect('/', {'error':'Invalid login details given, If you are a recruiter, login at recruiter page.'})
    else:
        return redirect('/')

def startupLogin(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_startup:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('recruiter:Profile',kwargs={'pk': user.id}))
                    return redirect('../recruiter/profile')
                else:
                    return render(request, "recruiter/RecruiterLanding.html",{'error':'User is flagged Inactive. Drop mail to internfair@udgam-iitg.in to reactivate your account'})
            else:
                return render(request, "recruiter/RecruiterLanding.html",{'error':'Invalid login details entered. If you are a student, login at student page.'})

                # return redirect('../recruiter',{'error':'User is flagged Inactive. Drop mail to internfair@udgam.in to reactivate your account'})
        else:
            return render(request, "recruiter/RecruiterLanding.html",{'error':'Invalid login details entered.'})

            # return redirect('../recruiter',{'error':'Invalid login details given. If you are a student, loginin at student page.'})
    else:
        return redirect('../recruiter')



@login_required
def AvailableInternships(request):
    if request.method == "POST":
        # print(request.POST)
        student = Students.objects.get(user=request.user)
        startup = request.POST["startup"]
        profile = request.POST["profile"]
        id = request.POST['id']
        internship = Intern_form.objects.get(pk=id)
        answers  = request.POST.getlist("answers")
        CV  = request.POST["CV"]
        app_count = student.intern_count
        if app_count < 5  :
            student.intern_count = app_count + 1
            student.save()
            app = InternApplication.objects.create(Intern=student,Internship = internship, Answers=answers,CV = CV)
            # app = [student.name,startup,profile,internship,answers]
            messages.success(request, f'You have successfully applied for internship in {startup} for  {profile} profile  ', '')
        else:
            messages.error(request, 'You have already applied for 5 Internships. You cannot apply for more. ','')

        return redirect('StudentProfile')



    else:
        available_internships = Intern_form.objects.all()

        template = "AvailableInternships.html"
        context = {'interns': available_internships}

        return render(request, template, context)


@login_required
def EditStudProfile(request, **kwargs):
    current_user = request.user
    student = Students.objects.get(user=current_user)
    if request.method=='POST':
        if request.POST['roll_number']:
            student.roll_number = request.POST['roll_number']
        if request.POST['department']:
            student.department = request.POST['department']
        if request.POST['bio']:
            student.bio = request.POST['bio']

        student.save()
    return HttpResponseRedirect(reverse('StudentProfile',kwargs={'pk': current_user.id}))







@login_required
def logout_view(request):
    logout(request)
    return redirect( 'index')

@login_required
def delete_app(request,**kwargs):
    print(kwargs)
    id = kwargs['pk']
    student = Students.objects.get(user = request.user)
    print(student)
    intern_app = InternApplication.objects.get(pk = id)
    intern_app.delete()

    print(intern_app)


    return HttpResponseRedirect(reverse('StudentProfile',kwargs={'pk': student.id}))



def intern_app_count(student):
    count = InternApplication.objects.filter(Intern__id= student.id).count()
    print(count)
    return count

internfair/templates/ApplyToCompanyCard.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/ApplyToCompanyCard.css' %}">
    <title>Google Application Page</title>
	<style type="text/css">
		html {height: 100%;}
		body {
			background-color: rgb(39, 39, 20)!important;
			background-size: cover;
			height: 100%;
		}
		
	</style>
</head>

<body>
    <div class="card">
        <div class="upperpart">
            <div class="image">
                <img src= "https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-webinar-optimizing-for-success-google-business-webinar-13.png"alt="loading..." id = "image">
            </div>
        </div>
        <div class = "name">
        <h1> Google </h1><br></div>
		<div class = "left">
		<table>
		
		
        <div class = "left">
		<div class = "lead">
            <p> PROFILE </p> </div>
        <div class = "answer">
            <p> Front-End Developer </p></div>
        <div class = "lead">
            <p> LOCATION  </p> </div>
        <div class = "answer">
            <p> Hyderabad </p></div>
        <div class = "lead">
            <p> STIPEND </p> </div>
        <div class = "answer">
            <p> N/A </p></div></div>
        <div class = "right"><div class = "lead">
            <p>ALLOWANCES </p> </div>
        <div class = "answer">
            <p> N/A </p></div>
        <div class = "lead">
            <p> REMARKS </p> </div>
        <div class = "answer">
            <p> You will be working from </p><p class = "x">home.</p> </p></div></div>
        <div class="button">
                    <ul class="ul">
                        <li>
                            <button type="button" class="apply">Apply</button>
                        </li>
                    </ul>
                </div>
                </table>
    </div>
    </div>
 </body>
</html>



        
            
        
	

internfair/templates/CancelApplicationCard.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/CancelApplicationCard.css' %}">
    <title>Google Application Page</title>
	<style type="text/css">
		html {height: 100%;}
		body {
			background-color: rgb(39, 39, 20)!important;
			background-size: cover;
			height: 100%;
		}
		
	</style>
</head>

<body>
    <div class="card">
        <div class="upperpart">
            <div class="image">
                <img src= "https://www.freepnglogos.com/uploads/google-logo-png/google-logo-png-webinar-optimizing-for-success-google-business-webinar-13.png"alt="loading..." id = "image">
            </div>
        </div>
        <div class = "name">
        <h1> Google </h1><br></div>
		<div class = "left">
		<table>
		
		
        <div class = "left">
		<div class = "lead">
            <p> PROFILE </p> </div>
        <div class = "answer">
            <p> Front-End Developer </p></div>
        <div class = "lead">
            <p> LOCATION  </p> </div>
        <div class = "answer">
            <p> Hyderabad </p></div>
        <div class = "lead">
            <p> STIPEND </p> </div>
        <div class = "answer">
            <p> N/A </p></div></div>
        <div class = "right"><div class = "lead">
            <p>ALLOWANCES </p> </div>
        <div class = "answer">
            <p> N/A </p></div>
        <div class = "lead">
            <p> REMARKS </p> </div>
        <div class = "answer">
            <p> You will be working from </p><p class = "x">home.</p> </p></div></div>
        <div class="button">
                    <ul class="ul">
                        <li>
                            <button type="button" class="cancel">Cancel Application</button>
                        </li>
                    </ul>
                </div>
                </table>
    </div>
 </body>
</html>



        
            
        
	

internfair/templates/CancelConfirmationCard.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	<title>Cancel Confirmation</title>
	<style type="text/css">
		html, body {height: 100%;}
		body {
			background-color: #696969;
		}
		@font-face {
		    font-family: 'GT Walsheim Pro';
		    src: local('GT Walsheim Pro Medium'), local('GT-Walsheim-Pro-Medium'),
		        url('GTWalsheimPro-Medium.woff2') format('woff2'),
		        url('GTWalsheimPro-Medium.woff') format('woff'),
		        url('GTWalsheimPro-Medium.ttf') format('truetype');
		    font-weight: 500;
		    font-style: normal;
		}
		.card-text {
			font-size: .9rem;
			font-family: "GT Walsheim Pro";
		}
		.btn-custom {
			color: #fff;
			background-color: #416EA8;
			border-color: #416EA8;
		}
		#company {
			text-decoration: underline;
		}
		#logo {
			width: 50px; height: 40px;
			margin: .5rem !important;
		}
		
	</style>
</head>
<body>
 	

 	<div class="d-flex container justify-content-center align-items-center"style= "height: 100%">
 		<div class="row justify-content-center" style="width: 100%;">
 			<div class=" col-12 col-sm-8 col-xl-6 bg-light d-flex justify-content-center" style="border-radius: 1rem !important">
				<div class="col-12 col-md-10 col-lg-9 col-xl-8 card-body text-center card-text">
				  	<img src="https://c7.uihere.com/files/557/90/534/google-logo-g-suite-google.jpg" id="logo">
				    <p class="m-0">Are you sure that you want to cancel your application for internship in</p>
				    <p id="company">Google</p>
		    		<a href="#" class="btn btn-custom py-1 px-3">Yes</a>
		    		<a href="#" class="btn py-1 px-3" style="color: #416EA8; text-decoration: underline; outline: none;">No</a>
		    	</div>
 			</div>
 		</div>
 	</div>

</body>
</html>

internfair/templates/InternshipQuestionsCard2.html
<!doctype html>
{% load static %}
<html lang="en">
  <head >
    <link rel="stylesheet" href="{% static 'css/InternshipQuestionsCard2.css' %}">

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>Internship Form</title>
  </head>
  <body>
    <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Launch Card
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
            <div class="title">
                Internship Form
            </div>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="prelim">
            Questions for preliminary interview
        </div>
            <label for="question1" class="question" class="ques">QUESTION 1</label>
            <div class="form-group">
                <input type="text" class="form-control" id="question1" >
            </div>
            <label for="question2" class="question">QUESTION 2</label>
            <div class="form-group">
                <input type="text" class="form-control" id="question2">
            </div>
            <label for="question3" class="question">QUESTION 3</label>
            <div class="form-group">
                <input type="text" class="form-control" id="question3" >
            </div>
        <div class="modal-footer">
            <div class="footer">
          <button type="button" class="btn btn-white back" data-dismiss="modal" >Back</button>
          <button type="button" class="btn btn-primary submit" data-target = "#question_card" >Submit</button>
            </div>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

internfair/templates/StudentLanding.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">    
    <title>Home-Student</title>
    <script type='text/javascript' src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
    <script type='text/javascript' src="http://netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/StudentLanding.css' %}">

</head>
<body>
    <nav class="navbar navbar-edit navbar-expand-lg navbar-light bg-light" style="padding: 1vh 8vw; box-shadow: 0px 2px 8px rgba(72, 74, 82, 0.08); background-color: #FFFFFF !important">
        <a class="brand" href="#" id="brand">Internfair</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse drop-menu" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="menu-item">
                <a href="#" class="nav-menu" style="margin-right: 8vw;">Home</a>
            </li>
            <li class="menu-item">
                <a href="mailto:internfair@udgam-iitg.ac.in" title="Send us Mail with any of your Query, We will respond you, at our earliest."class="nav-menu">Contact Us</a>
            </li>
          </ul>
          <a href="{% url 'StudentRegistration' %}"><button class="RegisterBtn">Register</button></a>
          
        </div>
      </nav>

      <br><br><br>
      <div class="container">
        <div class="row justify-content-center align-items-center" style="margin-top:5vh">
            <div class="col-lg-5 order-lg-1 order-md-1 order-12 col-md-6 col-10 temp" style="padding-left:10vw;">
                <span class="heading">Your first step to excel in your career</span>
                <br><br>
                <span class="quote">Internfair provides the perfect platform to land that first step</span>
                <br><br><br>
                <div class='form' style="width: 80%;">
                    <div class="row justify-content-end">
                        <div class="col-6">
                            <span class="studentLogin">Student Login</span>
                        </div>
                        <div class="col-6 text-right">
                            <a class="recruiter" href="{% url 'recruiter:RecruiterLanding' %}">I am a recruiter</a>
                        </div>
                    </div>
                    <form method='POST' action="{% url 'StudentLogin' %}">
                        {% csrf_token %}
                        <input type="text" name='Username' placeholder="Username" class="input">
                        <input type="password" name='Password' placeholder="Password" class="input">
                        <input type="submit" value="Login" class="login">
                    </form>
                    
                    <div class="row justify-content-end" style="margin-top: 24px;">
                        <div class="col-6">
                            <span class="recruiter"><a href="{% url 'StudentRegistration' %}">Don’t have an account?</a></span>
                        </div>
                        <div class="col-6 text-right">
                            <a class="recruiter" href="mailto:internfair@udgam-iitg.ac.in?subject=Send Me Password " title="Please Send a Mail with your Email id and Username, You will get it on mail">Forgot Password?</a>
                        </div>
                    </div>
                    
                </div>
                
                {% if error %}
                        <br>
                        <div class="row" style="padding-left:15px">
                        <div class="error col-9">
                        {{error}}
                        </div>
                        </div>
                        
                {% endif %}
             
            
            </div>
            <div class="col-lg-7 order-lg-2 order-md-2 order-1 text-center col-md-6 col-12" id="intro"  >
                <img class="sideImg" src="{% static 'image/sideImg.png' %}" alt="">

            </div>
       </div>
      </div>

      
</body>
</html>

internfair/templates/StudentRegistration.html
<!doctype html>
{% load static %}
{% load widget_tweaks %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="{% static 'css/StudentRegistration.css' %}">

  <title>Page1</title>
</head>

<body>


  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-brand" href="{% url 'StudentLogin' %}">Internfair</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active contact ">
          <a class="nav-link" href="mailto:internfair@udgam-iitg.ac.in" title="Send us Mail with any of your Query, We will respond you, at our earliest.">Contact Us</a>
        </li>
      </ul>
    </div>
    <form class="form-inline register">
      <a class="btn btn-primary " href="{% url 'StudentLogin' %}" role="button">Login</a>
    </form>
  </nav>




  <div class="head">
    Register to participate in Internfair
  </div>
  <form  method='POST' action="{% url 'StudentRegistration' %}" id="student_form">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group">
            {% render_field field class="form-control" placeholder=field.label%}
              {% for error in field.errors %}
                <span style="color:red">{{ error }}</span>
              {% endfor %}
    {% endfor %}
    {% if messages %}

          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %} style="color:red">{{ message }}</li>
          {% endfor %}

      {% endif %}
      <div>
        <button type="submit" class="btn btn-primary btn-lg btn-block regn">Register</button>
      </div>
      <br>
  </form>
  <div class="student"><a class="intern" href="{% url 'recruiter:RecruiterRegistration' %}"> I am a recruiter</a></div>

</body>

</html>